const pages = [
      {title:"Página 1 — Nosotros dos",intro:"Empezamos con frases sencillas sobre la pareja.",questions:[
        {instruction:"Completa la frase.",prompt:"1. Tu ___ ma copine.",options:["est","es","suis"],answer:1},
        {instruction:"Elige la respuesta correcta.",prompt:"2. Comment s’appelle ton copain ?",options:["Il habite français.","Il a Toulouse.","Il s’appelle Armand."],answer:2},
        {instruction:"Completa la frase.",prompt:"3. Nous ___ en couple.",options:["sommes","avons","êtes"],answer:0}]},
      {title:"Página 2 — La vida cotidiana",intro:"Verbos sencillos para hablar de todos los días.",questions:[
        {instruction:"Completa la frase.",prompt:"4. Le matin, je ___ un café.",options:["mange","bois","parle"],answer:1},
        {instruction:"Completa la frase.",prompt:"5. Tu ___ à Buenos Aires.",options:["habitons","habite","habites"],answer:2},
        {instruction:"Completa la frase.",prompt:"6. Nous ___ au téléphone le soir.",options:["parlons","parlez","parle"],answer:0}]},
      {title:"Página 3 — Amor y sentimientos",intro:"Decir lo que sientes con frases muy simples.",questions:[
        {instruction:"Elige la traducción correcta.",prompt:"7. « Te quiero. »",options:["Je te regarde.","Je t’aime.","Je te téléphone."],answer:1},
        {instruction:"Completa la frase.",prompt:"8. Tu me ___ beaucoup.",options:["manque","manquez","manques"],answer:2},
        {instruction:"Elige la frase correcta.",prompt:"9. ¿Cómo se dice « Me gusta cuando me besas »?",options:["J’aime quand tu m’embrasses.","Je suis quand tu embrasses.","J’aime tu me regarde."],answer:0}]},
      {title:"Página 4 — Una cita romántica",intro:"Preparar una cita y hablar de lo que llevas puesto.",questions:[
        {instruction:"Completa la frase.",prompt:"10. Notre rendez-vous est ___ soir.",options:["cette","ces","ce"],answer:2},
        {instruction:"Elige la traducción correcta.",prompt:"11. « Vemos una película juntos. »",options:["Nous regardons un film ensemble.","Nous mangeons le film demain.","Nous sommes un film."],answer:0},
        {instruction:"Completa la frase.",prompt:"12. Je porte ___ robe noire.",options:["un","une","des"],answer:1}]},
      {title:"Página 5 — El cuerpo y la atracción",intro:"Palabras sencillas para hablar de belleza y sensaciones.",questions:[
        {instruction:"Elige la respuesta correcta.",prompt:"13. Avec quoi est-ce qu’on embrasse ?",options:["Les lèvres","Les pieds","Les oreilles"],answer:0},
        {instruction:"Completa la frase.",prompt:"14. Tu as de très beaux ___.",options:["main","cheveu","yeux"],answer:2},
        {instruction:"Elige la traducción correcta.",prompt:"15. « Me gusta tu perfume. »",options:["J’aime ton téléphone.","J’aime ton parfum.","Je porte ton parfum."],answer:1}]},
      {title:"Página 6 — En casa",intro:"Acciones habituales para una noche juntos.",questions:[
        {instruction:"Completa la frase.",prompt:"16. Je prépare ___ dîner.",options:["la","le","les"],answer:1},
        {instruction:"Elige la traducción correcta.",prompt:"17. « Vamos al restaurante. »",options:["Nous sommes le restaurant.","Nous parlons au restaurant.","Nous allons au restaurant."],answer:2},
        {instruction:"Completa la frase.",prompt:"18. Après le travail, je ___ à la maison.",options:["rentre","rentrons","rentrez"],answer:0}]},
      {title:"Página 7 — Pequeñas instrucciones",intro:"Comprender algunas frases simples du professeur.",questions:[
        {instruction:"Elige la traducción correcta.",prompt:"19. « Cierra los ojos. »",options:["Ouvre la bouche.","Ferme les yeux.","Tourne la tête."],answer:1},
        {instruction:"Elige la traducción correcta.",prompt:"20. « Espera aquí. »",options:["Parle ici.","Regarde demain.","Attends ici."],answer:2},
        {instruction:"Elige la traducción correcta.",prompt:"21. « Dime lo que quieres. »",options:["Dis-moi ce que tu veux.","Je veux ton téléphone.","Tu dis demain."],answer:0}]},
      {title:"Página 8 — Deseo e intensidad",intro:"Expresar lo que quieres de manera sencilla.",questions:[
        {instruction:"Elige la traducción correcta.",prompt:"22. « Un poco más. »",options:["Moins vite.","Très loin.","Encore un peu."],answer:2},
        {instruction:"Elige la traducción correcta.",prompt:"23. « Más despacio. »",options:["Plus doucement.","Plus grand.","Moins près."],answer:0},
        {instruction:"Completa la frase.",prompt:"24. Ne t’arrête ___ maintenant.",options:["rien","pas","jamais de"],answer:1}]},
      {title:"Página 9 — Esta noche y mañana",intro:"Hablar de horarios y de planes sencillos.",questions:[
        {instruction:"Elige la pregunta correcta.",prompt:"25. La réponse est : « À vingt-deux heures. »",options:["À quelle heure ?","Quel âge as-tu ?","Où habites-tu ?"],answer:0},
        {instruction:"Completa la frase.",prompt:"26. Demain, je ___ travailler.",options:["va","allez","vais"],answer:2},
        {instruction:"Elige la frase correcta.",prompt:"27. ¿Cómo se dice « Te llamo esta noche »?",options:["Je te vois hier.","Je t’appelle ce soir.","Je parle demain soir toi."],answer:1}]},
      {title:"Página 10 — Comprensión final",intro:"Una última lectura antes de terminar el desafío.",reading:"Ce soir, Ailin et Armand ont rendez-vous en vidéo. Ils parlent de leur journée, rient et se disent des mots doux. Ensuite, ils jouent en français. Armand valide chaque page avant d’envoyer la suivante. Quand Ailin réussit une page parfaite, la récompense alterne : une photo d’Armand, puis un ordre à lui donner.",questions:[
        {instruction:"Lee el texto y elige la respuesta correcta.",prompt:"28. Comment est leur rendez-vous ?",options:["Au restaurant","À l’école","En vidéo"],answer:2},
        {instruction:"Lee el texto y elige la respuesta correcta.",prompt:"29. Qui valide chaque page ?",options:["Armand","Le téléphone","Le restaurant"],answer:0},
        {instruction:"Lee el texto y elige la respuesta correcta.",prompt:"30. Que peut gagner Ailin après une page parfaite ?",options:["Une photo ou le droit de donner un ordre","Un billet d’avion","Un nouveau téléphone"],answer:0}]}
    ];

    const bonuses = [
      "J’aime quand tu décides quand je peux me toucher.",
      "J’aime quand tu me donnes des ordres.",
      "J’aimerais te donner des ordres.",
      "J’aime que tu m’attaches.",
      "Je veux m’asseoir sur ton visage."
    ];
    const gages=["Répète les trois bonnes réponses en disant « Monsieur le professeur ».","Attends une minute sans te toucher, puis demande la permission en français.","Dis trois fois : « Je vais être une élève très sage. »","Décris en une phrase française la récompense que tu veux gagner.","Reste immobile pendant trente secondes avant la prochaine question."];

    let peer=null,conn=null,retryTimer=null,sessionCode="",pendingSubmission=null;
    let currentPage=0,activeBonus=null,pendingContinue=null;
    const answers={},bonusAnswers={},pageScores=Array(pages.length).fill(null),bonusValidated=Array(bonuses.length).fill(false);
    const quiz=document.getElementById("quiz");

    function makeId(){return `${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
    function getGameLevel(){let level=1;pageScores.forEach(score=>{if(score===3)level+=1;else if(score===2)level+=.5;else if(score===0)level-=.5});bonusValidated.forEach(ok=>{if(ok)level+=.5});return Math.max(0,Math.min(10,level))}
    function projectedLevel(kind,score){let level=getGameLevel();if(kind==="bonus")level+=.5;else if(score===3)level+=1;else if(score===2)level+=.5;else if(score===0)level-=.5;return Math.max(0,Math.min(10,level))}
    function formatLevel(level){return Number.isInteger(level)?String(level):String(level).replace(".",",")}
    function getLevelStatus(level){const band=Math.floor(level);if(band<=2)return"Solo teasing";if(band<=4)return"Teasing intenso";if(band<=6)return"Vibración suave";if(band<=8)return"Vibración media";return"Vibración fuerte"}
    function updateIntensity(deltaText=""){const level=getGameLevel(),percent=Math.max(0,Math.min(100,level*10));document.getElementById("levelValue").textContent=formatLevel(level);document.getElementById("levelStatus").textContent=getLevelStatus(level);const delta=document.getElementById("levelDelta");delta.textContent=deltaText;delta.classList.remove("flash");if(deltaText){void delta.offsetWidth;delta.classList.add("flash")}const fill=document.getElementById("meterFill"),marker=document.getElementById("meterMarker");if(window.matchMedia("(max-width:900px)").matches){fill.style.width=`${percent}%`;marker.style.left=`${percent}%`}else{fill.style.height=`${percent}%`;marker.style.bottom=`${percent}%`}}
    function quizStepIndex(pageIndex){return pageIndex+Math.floor(pageIndex/2)}function bonusStepIndex(bonusIndex){return bonusIndex*3+2}
    function updateProgress(stepIndex,label){document.getElementById("progress").style.width=`${((stepIndex+1)/15)*100}%`;document.getElementById("pageCounter").textContent=label}

    function setConnectionState(text,status="wait"){document.getElementById("connectionState").innerHTML=`<span class="dot ${status}"></span>${text}`;const w=document.getElementById("waitingConnection");if(w)w.textContent=text}
    function startConnection(){sessionCode=document.getElementById("sessionCode").value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"");if(!sessionCode){setConnectionState("Entre le code du professeur","");return}localStorage.setItem("defiSessionCode",sessionCode);document.getElementById("connectButton").disabled=true;setConnectionState("Connexion au professeur…","wait");if(peer&&!peer.destroyed)peer.destroy();peer=new Peer();peer.on("open",()=>connectToProfessor());peer.on("error",()=>scheduleRetry());peer.on("disconnected",()=>{try{peer.reconnect()}catch(e){scheduleRetry()}})}
    function connectToProfessor(){if(!peer||peer.destroyed||!peer.open)return;if(conn&&conn.open)return;try{conn=peer.connect(`defi-prof-${sessionCode.toLowerCase()}`,{reliable:true,metadata:{role:"student"}});conn.on("open",()=>{clearTimeout(retryTimer);setConnectionState("Connectée au professeur","ok");document.getElementById("connectScreen").classList.add("hidden");document.getElementById("gameShell").classList.remove("hidden");conn.send({type:"hello",currentPage,activeBonus,level:getGameLevel(),stepsCompleted:pageScores.filter(s=>s!==null).length+bonusValidated.filter(Boolean).length});if(pendingSubmission)conn.send(pendingSubmission);if(!quiz.innerHTML)renderPage()});conn.on("data",handleProfessorMessage);conn.on("close",()=>scheduleRetry());conn.on("error",()=>scheduleRetry())}catch(e){scheduleRetry()}}
    function scheduleRetry(){setConnectionState("Professeur indisponible — nouvelle tentative…","wait");document.getElementById("connectButton").disabled=false;clearTimeout(retryTimer);retryTimer=setTimeout(()=>{if(peer&&peer.open)connectToProfessor();else if(sessionCode)startConnection()},3000)}
    function handleProfessorMessage(data){if(!data||typeof data!=="object")return;if(data.type==="approval"&&pendingSubmission&&data.submissionId===pendingSubmission.submissionId)applyApproval(pendingSubmission);if(data.type==="rejection"&&pendingSubmission&&data.submissionId===pendingSubmission.submissionId){pendingSubmission=null;document.getElementById("waitingModal").classList.remove("open");const notice=document.getElementById("reviewNotice");if(notice){notice.textContent=data.message||"Le professeur te demande de vérifier tes réponses.";notice.classList.remove("hidden")}enableCurrentForm(true)}}
    function enableCurrentForm(enabled){document.querySelectorAll("#quiz input,#quiz button").forEach(el=>el.disabled=!enabled)}

    function renderPage(){activeBonus=null;const page=pages[currentPage];let html=`<div class="page"><h2>${page.title}</h2><p class="page-intro">${page.intro}</p><div class="notice hidden" id="reviewNotice"></div>`;if(page.reading)html+=`<div class="reading">${page.reading}</div>`;page.questions.forEach((q,localIndex)=>{const globalIndex=currentPage*3+localIndex,chosen=answers[globalIndex];html+=`<div class="question"><div class="instruction">${q.instruction}</div><div class="prompt">${q.prompt}</div>`;q.options.forEach((option,optionIndex)=>{html+=`<label class="option"><input type="radio" name="q${globalIndex}" value="${optionIndex}" ${chosen===optionIndex?"checked":""} onchange="saveAnswer(${globalIndex},${optionIndex})"><span>${String.fromCharCode(65+optionIndex)}. ${option}</span></label>`});html+=`</div>`});html+=`<div class="validation-warning" id="validationWarning">Responde las tres preguntas antes de continuar.</div><div class="controls"><button class="primary" onclick="submitCurrentPage()">Envoyer au professeur</button></div></div>`;quiz.innerHTML=html;updateProgress(quizStepIndex(currentPage),`Página ${currentPage+1} de ${pages.length}`);updateIntensity();window.scrollTo({top:0,behavior:"smooth"})}
    function renderBonus(bonusIndex){activeBonus=bonusIndex;const choice=bonusAnswers[bonusIndex];quiz.innerHTML=`<div class="bonus-page"><span class="bonus-chip">Bonus intime ${bonusIndex+1} / ${bonuses.length}</span><h2>Vrai ou faux ?</h2><p class="page-intro">Réponds simplement et honnêtement.</p><div class="notice hidden" id="reviewNotice"></div><div class="bonus-question"><div class="bonus-fr">${bonuses[bonusIndex]}</div><p class="bonus-points">Réponse validée : +0,5 point</p><label class="option"><input type="radio" name="bonus${bonusIndex}" value="true" ${choice===true?"checked":""} onchange="saveBonusAnswer(${bonusIndex},true)"><span>Vrai</span></label><label class="option"><input type="radio" name="bonus${bonusIndex}" value="false" ${choice===false?"checked":""} onchange="saveBonusAnswer(${bonusIndex},false)"><span>Faux</span></label><div class="validation-warning" id="validationWarning">Choisis Vrai ou Faux avant de continuer.</div></div><div class="controls"><button class="primary" onclick="submitBonus()">Envoyer au professeur</button></div></div>`;updateProgress(bonusStepIndex(bonusIndex),`Bonus ${bonusIndex+1} sur ${bonuses.length}`);updateIntensity();window.scrollTo({top:0,behavior:"smooth"})}
    function saveAnswer(i,v){answers[i]=v;hideWarning()}function saveBonusAnswer(i,v){bonusAnswers[i]=v;hideWarning()}function hideWarning(){const w=document.getElementById("validationWarning");if(w)w.style.display="none"}
    function perfectReward(){const previous=pageScores.filter(score=>score===3).length;return previous%2===0?{type:"photo",text:"Tu as gagné une photo d’Armand 📸"}:{type:"order",text:"Tu peux donner un ordre à Armand 😈"}}
    function submitCurrentPage(){const start=currentPage*3;if(![0,1,2].every(o=>answers[start+o]!==undefined)){document.getElementById("validationWarning").style.display="block";return}let score=0;const details=pages[currentPage].questions.map((q,i)=>{const selected=answers[start+i];if(selected===q.answer)score++;return{number:start+i+1,prompt:q.prompt,selectedIndex:selected,selected:q.options[selected],correctIndex:q.answer,correct:q.options[q.answer],isCorrect:selected===q.answer}});const reward=score===3?perfectReward():null;pendingSubmission={type:"submission",submissionId:makeId(),kind:"quiz",pageIndex:currentPage,score,details,reward,gage:score===0?gages[currentPage%gages.length]:null,levelBefore:getGameLevel(),levelAfter:projectedLevel("quiz",score)};sendSubmission()}
    function submitBonus(){if(bonusAnswers[activeBonus]===undefined){document.getElementById("validationWarning").style.display="block";return}pendingSubmission={type:"submission",submissionId:makeId(),kind:"bonus",bonusIndex:activeBonus,statement:bonuses[activeBonus],answer:bonusAnswers[activeBonus],levelBefore:getGameLevel(),levelAfter:projectedLevel("bonus")};sendSubmission()}
    function sendSubmission(){if(!conn||!conn.open){scheduleRetry();return}enableCurrentForm(false);conn.send(pendingSubmission);document.getElementById("waitingModal").classList.add("open")}
    function deltaForScore(score){if(score===3)return"+1 point";if(score===2)return"+0,5 point";if(score===0)return"−0,5 point";return"Sans changement"}
    function applyApproval(submission){pendingSubmission=null;document.getElementById("waitingModal").classList.remove("open");if(submission.kind==="bonus"){bonusValidated[submission.bonusIndex]=true;updateIntensity("+0,5 point");showBonusFeedback();pendingContinue=()=>continueAfterBonus(submission.bonusIndex);return}pageScores[submission.pageIndex]=submission.score;updateIntensity(deltaForScore(submission.score));showQuizFeedback(submission);pendingContinue=()=>continueAfterPage(submission.pageIndex)}
    function showBonusFeedback(){document.getElementById("modalContent").innerHTML=`<h2 id="feedbackTitle">💜 Bonus validé</h2><p>Ta réponse a été envoyée au professeur.</p><div class="modal-delta">+0,5 point</div>`;document.getElementById("feedbackModal").classList.add("open")}
    function showQuizFeedback(submission){let title,text;if(submission.score===3){title="🔥 3 de 3 — Parfait";text=submission.reward.text}else if(submission.score===2){title="💜 2 de 3 — Très bien";text="Le niveau augmente de 0,5 point."}else if(submission.score===1){title="😏 1 de 3 — Encore un effort";text="Le niveau reste identique."}else{title="⏳ 0 de 3 — Gage";text="Le niveau baisse de 0,5 point."}const corrections=submission.details.filter(d=>!d.isCorrect).map(d=>`Question ${d.number} : la bonne réponse est « ${d.correct} ».`);const correctionHtml=corrections.length?`<h3>Corrections</h3><ul class="correction-list">${corrections.map(x=>`<li>${x}</li>`).join("")}</ul>`:`<p class="perfect">Les trois réponses sont correctes !</p>`;const gage=submission.gage?`<p><strong>Gage :</strong> ${submission.gage}</p>`:"";document.getElementById("modalContent").innerHTML=`<h2 id="feedbackTitle">${title}</h2><p><strong>${text}</strong></p><div class="modal-delta">${deltaForScore(submission.score)}</div>${gage}${correctionHtml}`;document.getElementById("feedbackModal").classList.add("open")}
    function closeFeedbackAndContinue(){document.getElementById("feedbackModal").classList.remove("open");if(pendingContinue){const fn=pendingContinue;pendingContinue=null;fn()}}
    function continueAfterPage(pageIndex){if(pageIndex%2===1)renderBonus(Math.floor(pageIndex/2));else if(pageIndex<pages.length-1){currentPage=pageIndex+1;renderPage()}else finishQuiz()}
    function continueAfterBonus(bonusIndex){if(bonusIndex===bonuses.length-1)finishQuiz();else{currentPage=(bonusIndex+1)*2;renderPage()}}
    function finishQuiz(){quiz.style.display="none";document.getElementById("result").style.display="block";document.getElementById("resultMessage").textContent=`Niveau final : ${formatLevel(getGameLevel())}/10 — ${getLevelStatus(getGameLevel())}.`;document.getElementById("pageCounter").textContent="Défi terminé";document.getElementById("progress").style.width="100%";updateIntensity();if(conn&&conn.open)conn.send({type:"finished",level:getGameLevel(),pageScores,bonusAnswers});window.scrollTo({top:0,behavior:"smooth"})}

    window.addEventListener("resize",()=>updateIntensity());
    const codeFromUrl=new URLSearchParams(location.search).get("code")||localStorage.getItem("defiSessionCode")||"";if(codeFromUrl){document.getElementById("sessionCode").value=codeFromUrl.toUpperCase();setTimeout(startConnection,250)}
